version: 1.0.{build}

platform:
  - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: -G"Visual Studio 14 2015 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: -G"Visual Studio 15 2017 Win64"

build_script:
  - mkdir build
  - cd build
  - cmake %CMAKE_GENERATOR% ../
  - cmake --build . --config Release
  - ctest -C Release
